/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Fabian Orrego (https://sketchfab.com/fabian_orrego)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wrath-of-the-dragon-bda2c373806747a28812c9d88bf55dfa
Title: Wrath of the Dragon
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import scene from '../assets/3d/dragon.glb'
export function Dragon(props) {
  const { nodes, materials } = useGLTF(scene)
  return (
    <group {...props} dispose={null}>
      <group name='Sketchfab_model' rotation={[-Math.PI / 2, 0, 0]}>
        <group
          name='Armature'
          position={[3.21228, -56.97082, 24.2407]}
          rotation={[0, 0, -Math.PI]}>
          <primitive object={nodes.Armature_rootJoint} />
          <skinnedMesh
            name='Dragon_0'
            geometry={nodes.Dragon_0.geometry}
            material={materials['rock_004.014_0']}
            skeleton={nodes.Dragon_0.skeleton}
          />
          <mesh
            name='Tooth_Lower_0'
            castShadow
            receiveShadow
            geometry={nodes.Tooth_Lower_0.geometry}
            material={materials['rock_004.014_0']}
            position={[-2.80546, -6.39981, 14.08168]}
            rotation={[1.42717222, 0.138234, -0.00267343]}
            scale={[1.25330322, 1.25363279, 1.25292233]}
          />
          <mesh
            name='Tooth_Upper_0'
            castShadow
            receiveShadow
            geometry={nodes.Tooth_Upper_0.geometry}
            material={materials['rock_004.014_0']}
            position={[-2.4152, -8.99216, 15.60295]}
            rotation={[0.80376456, 0.11403809, 0.07833855]}
            scale={[1.25330345, 1.2535963, 1.25295308]}
          />
        </group>
        <group
          name='Mountain-2000'
          position={[-15.40913, 143.67784, 31.76434]}
          rotation={[0, 0, 2.90782909]}
          scale={[0.99999846, 0.99999846, 1]}>
          <mesh
            name='Mountain-2000_0'
            castShadow
            receiveShadow
            geometry={nodes['Mountain-2000_0'].geometry}
            material={materials['rock_004.014_0']}
          />
          <mesh
            name='Mountain-2000_0_1'
            castShadow
            receiveShadow
            geometry={nodes['Mountain-2000_0_1'].geometry}
            material={materials['rock_004.014_0']}
          />
        </group>
        <group
          name='Armature001'
          position={[9.35776, 26.97051, 4.45193]}
          rotation={[0, 0, -Math.PI]}>
          <primitive object={nodes.Armature001_rootJoint} />
          <skinnedMesh
            name='Dragon001_0'
            geometry={nodes.Dragon001_0.geometry}
            material={materials['rock_004.014_0']}
            skeleton={nodes.Dragon001_0.skeleton}
          />
          <mesh
            name='Tooth_Lower001_0'
            castShadow
            receiveShadow
            geometry={nodes.Tooth_Lower001_0.geometry}
            material={materials['rock_004.014_0']}
            position={[3.44342, -19.1431, -2.21482]}
            rotation={[0.46710838, 0.31787429, 0.62585532]}
            scale={[0.75665248, 0.75674494, 0.75653132]}
          />
          <mesh
            name='Tooth_Upper001_0'
            castShadow
            receiveShadow
            geometry={nodes.Tooth_Upper001_0.geometry}
            material={materials['rock_004.014_0']}
            position={[3.76499, -19.61314, -0.83098]}
            rotation={[0.19482158, 0.11180687, 0.68461852]}
            scale={[0.75664553, 0.75664262, 0.7566256]}
          />
        </group>
        <mesh
          name='MagicSpell001_0'
          castShadow
          receiveShadow
          geometry={nodes.MagicSpell001_0.geometry}
          material={materials.TranslucencyMaterial}
          position={[0.31447, 51.42384, 0.6646]}
          rotation={[0, 0, 0.7398304]}
          scale={[0.99999606, 0.99999606, 1]}
        />
        <mesh
          name='LeaderWarrior_0'
          castShadow
          receiveShadow
          geometry={nodes.LeaderWarrior_0.geometry}
          material={materials['rock_004.014_0']}
          position={[0.31447, 51.42384, 0.6646]}
          rotation={[0, 0, 0.7398304]}
          scale={[0.99999606, 0.99999606, 1]}
        />
        <mesh
          name='Wizard_0'
          castShadow
          receiveShadow
          geometry={nodes.Wizard_0.geometry}
          material={materials['rock_004.014_0']}
          position={[-1.74008, -15.48568, 0]}
        />
        <mesh
          name='rock_004011_0'
          castShadow
          receiveShadow
          geometry={nodes.rock_004011_0.geometry}
          material={materials['rock_004.014_0']}
          position={[0.42807, 51.16849, 1.80875]}
          rotation={[0, 0, 0.81435526]}
          scale={[2.1753148, 2.1753148, 0.85281]}
        />
        <mesh
          name='rock_004014_0'
          castShadow
          receiveShadow
          geometry={nodes.rock_004014_0.geometry}
          material={materials['rock_004.014_0']}
          position={[-1.53042, -15.56416, 1.11335]}
          rotation={[0, 0, 1.56231011]}
          scale={[2.17531833, 2.17531833, 0.85281]}
        />
      </group>
    </group>
  )
}

useGLTF.preload(scene)
